# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b403bab2032c83b9bfff43ea6857bc6036816746e176a26eb4a5c706fabccf35e4fcd5ff7c8bff2e0b1af6a74aeff9e22efe7bdc76b45ec8b4bdf50e5e520145

test:
  secret_key_base: db4366cfeca84182d2f19d5344ea07c44d8cb2cd2b797eb2908a9ad31e0166d37057a7cf221f9afb1cdfe072c215eca531741c069a0f2e33ce0256cac15c0ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
